package org.feidian.hzau.bbs.common.model;

import org.feidian.hzau.bbs.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

}
